### ISSUE TITLE
RtfDocument, StyleBlock and Painter are not exposed in the public API

### ISSUE THREAD

**Issue by CBenoit** [d0rianb/rtf-parser#1]
Hi! Thanks for the crate, it looks nice.

I open this issue because it looks like items that _should_ be publicly exposed are not:
https://github.com/d0rianb/rtf-parser/blob/dfad4d3d15643d685abe7d9dd3953f8888e90068/src/parser.rs#L9-L28

Which means that it’s not possible to use the output of the `parse` method:
![image](https://github.com/d0rianb/rtf-parser/assets/3809077/3d24e3c0-0f0e-40a5-b96b-e29bdea0bccd)

`Painter` is exposed:
![image](https://github.com/d0rianb/rtf-parser/assets/3809077/8b1cd601-4d30-4d22-9b5b-144a47c8b249)

But none of its fields are:
![image](https://github.com/d0rianb/rtf-parser/assets/3809077/8dc2a44a-e064-4433-ab19-28f1126b8b42)

So we can’t do much with it either.

**Comment by d0rianb** [comment]
Thanks for the feedback, it's has been solved in [f9537d6](https://github.com/d0rianb/rtf-parser/commit/f9537d654ec76508a5e144ad9958b2fbe4d8b868).

**Comment by CBenoit** [comment]
Thank you! It seems `RtfDocument` and `StyleBlock` are still not exposed. I opened a PR for that: https://github.com/d0rianb/rtf-parser/pull/2
